#  Copyright (c) 2020. Maverick Labs
#    This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU Affero General Public License as,
#   published by the Free Software Foundation, either version 3 of the
#   License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.

from enum import Enum

from django.utils.translation import gettext as _

PUBLIC_KEY_LENGTH_ACADEMIC_YEAR = 3
PUBLIC_KEY_LENGTH_SCHOOL = 3
PUBLIC_KEY_LENGTH_CLASSROOM = 3
PUBLIC_KEY_LENGTH_NGO = 4
PUBLIC_KEY_LENGTH_LEVEL = 4
PUBLIC_KEY_LENGTH_BOOK = 12
PUBLIC_KEY_LENGTH_USER = 8
PUBLIC_KEY_LENGTH_STUDENT = 6
PUBLIC_KEY_LENGTH_SESSION = 12
LENGTH_QR_CODE_SVG_FILENAME = 10
LENGTH_TOKEN = 20
LENGTH_NOTE_FIELD = 500
LENGTH_RESET_PASSWORD_TOKEN = 10
API_URL = 'http://192.168.0.2/reset_password/'
LENGTH_BOOK_NAME_FIELD = 100
LENGTH_BOOK_AUTHOR_FIELD = 100
LENGTH_BOOK_PUBLISHER_FIELD = 100
LENGTH_SCHOOL_NAME_FIELD = 100
LENGTH_SCHOOL_ADDRESS_FIELD = 300
DESIRED_QR_WIDTH_AND_HEIGHT = 66


class GroupType(Enum):
    NGO_ADMIN = 'NGO Admin'
    READ_ADMIN = 'READ Admin'
    BOOK_FAIRY = 'Book Fairy'
    SUPERVISOR = 'Supervisor'
    FUNDER = 'Funder'


GROUPS = [GroupType.NGO_ADMIN, GroupType.READ_ADMIN, GroupType.BOOK_FAIRY, GroupType.SUPERVISOR, GroupType.FUNDER]

BOOK_LEVEL_1 = 'BOOK_LEVEL_1'
BOOK_LEVEL_2 = 'BOOK_LEVEL_2'
BOOK_LEVEL_3 = 'BOOK_LEVEL_3'
BOOK_LEVEL_4 = 'BOOK_LEVEL_4'

BOOK_LEVELS = [BOOK_LEVEL_1, BOOK_LEVEL_2, BOOK_LEVEL_3, BOOK_LEVEL_4]

SCHOOL_MEDIUM_ENGLISH = 'SCHOOL_MEDIUM_ENGLISH'
SCHOOL_MEDIUM_MARATHI = 'SCHOOL_MEDIUM_MARATHI'
SCHOOL_MEDIUM_URDU = 'SCHOOL_MEDIUM_URDU'
SCHOOL_MEDIUM_HINDI = 'SCHOOL_MEDIUM_HINDI'
SCHOOL_MEDIUM_KANNADA = 'SCHOOL_MEDIUM_KANNADA'
_("SCHOOL_MEDIUM_ENGLISH")
_("SCHOOL_MEDIUM_MARATHI")
_("SCHOOL_MEDIUM_URDU")
_("SCHOOL_MEDIUM_HINDI")
_("SCHOOL_MEDIUM_KANNADA")

READ_SESSION_PENDING = "PENDING"
READ_SESSION_EVALUATED_NOT_VERIFIED = "EVALUATED_NOT_VERIFIED"
READ_SESSION_UPCOMING = "UPCOMING"

MEDIUMS = [SCHOOL_MEDIUM_ENGLISH, SCHOOL_MEDIUM_MARATHI, SCHOOL_MEDIUM_URDU, SCHOOL_MEDIUM_HINDI, SCHOOL_MEDIUM_KANNADA]

SCHOOL_TYPE_PCMC = "SCHOOL_TYPE_PCMC"
SCHOOL_TYPE_PMC = "SCHOOL_TYPE_PMC"
SCHOOL_TYPE_ZP = "SCHOOL_TYPE_ZP"
SCHOOL_TYPE_PRIVATE = "SCHOOL_TYPE_PRIVATE"
_("SCHOOL_TYPE_PCMC")
_("SCHOOL_TYPE_PMC")
_("SCHOOL_TYPE_ZP")
_("SCHOOL_TYPE_PRIVATE")

SCHOOL_TYPES = [SCHOOL_TYPE_PCMC, SCHOOL_TYPE_PMC, SCHOOL_TYPE_ZP, SCHOOL_TYPE_PRIVATE]

SCHOOL_CATEGORY_BOYS = "SCHOOL_CATEGORY_BOYS"
SCHOOL_CATEGORY_GIRLS = "SCHOOL_CATEGORY_GIRLS"
SCHOOL_CATEGORY_CO_ED = "SCHOOL_CATEGORY_CO_ED"
_("SCHOOL_CATEGORY_BOYS")
_("SCHOOL_CATEGORY_GIRLS")
_("SCHOOL_CATEGORY_CO_ED")

SCHOOL_CATEGORY = [SCHOOL_CATEGORY_BOYS, SCHOOL_CATEGORY_GIRLS, SCHOOL_CATEGORY_CO_ED]

STANDARD_I = "STANDARD_I"
STANDARD_II = "STANDARD_II"
STANDARD_III = "STANDARD_III"
STANDARD_IV = "STANDARD_IV"
STANDARD_V = "STANDARD_V"
STANDARD_VI = "STANDARD_VI"
STANDARD_VII = "STANDARD_VII"

STANDARDS = [STANDARD_I, STANDARD_II, STANDARD_III, STANDARD_IV, STANDARD_V, STANDARD_VI, STANDARD_VII]

ACADEMIC_YEAR_18_19 = "AY 18-19"
ACADEMIC_YEAR_19_20 = "AY 19-20"
ACADEMIC_YEAR_20_21 = "AY 20-21"
ACADEMIC_YEAR_21_22 = "AY 21-22"
ACADEMIC_YEAR_22_23 = "AY 22-23"
ACADEMIC_YEAR_23_24 = "AY 23-24"
ACADEMIC_YEAR_24_25 = "AY 24-25"
ACADEMIC_YEAR_25_26 = "AY 25-26"
ACADEMIC_YEAR_26_27 = "AY 26-27"
ACADEMIC_YEAR_27_28 = "AY 27-28"
ACADEMIC_YEAR_28_29 = "AY 28-29"

ACADEMIC_YEARS = [ACADEMIC_YEAR_18_19, ACADEMIC_YEAR_19_20, ACADEMIC_YEAR_20_21, ACADEMIC_YEAR_21_22,
                  ACADEMIC_YEAR_22_23,
                  ACADEMIC_YEAR_23_24, ACADEMIC_YEAR_24_25, ACADEMIC_YEAR_25_26, ACADEMIC_YEAR_26_27,
                  ACADEMIC_YEAR_27_28,
                  ACADEMIC_YEAR_28_29]

MALE = "MALE"
FEMALE = "FEMALE"

SESSION_ATTENDED = "PRESENT"
SESSION_NOT_ATTENDED = "ABSENT"

REGULAR = "READ_SESSION_REGULAR"
EVALUATION = "READ_SESSION_EVALUATION"
BOOK_LENDING = "READ_SESSION_BOOK_LENDING"

SESSION_EVALUATED = "evaluated"
SESSION_NON_EVALUATED = "non evaluated"

USERS_EXCEL_FIELDS = ['Key', 'Username', 'First name', 'Middle name', 'Last name', 'Email address', 'Role']
STUDENTS_EXCEL_FIELDS = ['Key', 'First name', 'Middle name', 'Last name', 'Address', 'Gender', 'Mother tongue',
                         'Birth Date', 'Has Attended Preschool']
BOOKS_EXCEL_FIELDS = ['Key', 'Name', 'Level', 'Author', 'Publisher', 'Price']
BOOKS_AND_INVENTORY_EXCEL_FIELDS = ['Key', 'Name', 'Level', 'Author', 'Publisher', 'Price', 'Serial', 'Copies'
                                    ]
INVENTORY_BOOKS_EXCEL_FIELDS = ['Key', 'Serial Number', 'Status', 'Year of purchase']
SCHOOLS_EXCEL_FIELDS = ['Key', 'Name', 'Address', 'Pincode', 'Ward Number', 'School Number', 'Category', 'Type',
                        'Medium', 'Organization Name', 'Year of intervention']
USER_WORKSHEET_NAME = 'Users'
BOOK_WORKSHEET_NAME = 'Books'
STUDENT_WORKSHEET_NAME = 'Students'
INVENTORY_BOOK_WORKSHEET_NAME = 'Inventory'
SCHOOL_WORKSHEET_NAME = 'Schools'
DEFAULT_WORKSHEET_NAME = 'Sheet1'


class FileType(Enum):
    USER = 0
    BOOK = 1
    STUDENT = 2
    INVENTORY = 3
    SCHOOL = 4


MESSAGE_KEY = 'message'


def ERROR_400_JSON():
    return {MESSAGE_KEY: _('ERROR_MESSAGE_400')}


def ERROR_403_JSON():
    return {MESSAGE_KEY: _('ERROR_MESSAGE_403')}


def ERROR_404_JSON():
    return {MESSAGE_KEY: _('ERROR_MESSAGE_404')}


def ERROR_500_JSON():
    return {MESSAGE_KEY: _('ERROR_MESSAGE_500')}


def ERROR_LOGIN_1_JSON():
    return {MESSAGE_KEY: _('INCORRECT_USERNAME')}


def ERROR_LOGIN_2_JSON():
    return {MESSAGE_KEY: _('INCORRECT_PASSWORD')}


def ERROR_LOGIN_3_JSON():
    return {MESSAGE_KEY: _('LOGIN_UNAUTHORIZED_ERROR')}


def ERROR_LOGIN_4_JSON():
    return {MESSAGE_KEY: _('INCORRECT_USER_CONFIG')}


def ERROR_LOGIN_5_JSON():
    return {MESSAGE_KEY: _('UNABLE_TO_LOGIN')}


def SUCCESS_LOGIN_1_JSON():
    return {MESSAGE_KEY: _('SUCCESSFUL_LOGIN')}


def SUCCESS_LOGOUT_1_JSON():
    return {MESSAGE_KEY: _('SUCCESSFUL_LOGOUT')}


def ERROR_LOGOUT_1_JSON():
    return {MESSAGE_KEY: _('LOGOUT_UNAUTHORIZED_ERROR')}


def ERROR_SERIALIZER_400_JSON():
    return {MESSAGE_KEY: _('ERROR_SERIALIZER_400')}


def SUCCESS_PUT_JSON():
    return {MESSAGE_KEY: _('SUCCESS_PUT_JSON')}


def SUCCESS_LANGUAGE_CHANGE_JSON():
    return {MESSAGE_KEY: _('SUCCESS_LANGUAGE_CHANGE')}


# SCHOOL FIELDS LABELS
_("FIELD_LABEL_SCHOOL_NAME")
_("FIELD_LABEL_SCHOOL_ADDRESS")
_("FIELD_LABEL_SCHOOL_PIN_CODE")
_("FIELD_LABEL_SCHOOL_WARD_NUMBER")
_("FIELD_LABEL_SCHOOL_LATITUDE")
_("FIELD_LABEL_SCHOOL_LONGITUDE")
_("FIELD_LABEL_SCHOOL_SCHOOL_NUMBER")
_("FIELD_LABEL_SCHOOL_SCHOOL_CATEGORY")
_("FIELD_LABEL_SCHOOL_SCHOOL_TYPE")
_("FIELD_LABEL_SCHOOL_MEDIUM")
_("FIELD_LABEL_SCHOOL_ORGANIZATION_NAME")
_("FIELD_LABEL_SCHOOL_YEAR_OF_INTERVENTION")

# BOOK FIELDS LABELS
_("FIELD_LABEL_BOOK_NAME")
_("FIELD_LABEL_BOOK_LEVEL")
_("FIELD_LABEL_BOOK_AUTHOR")
_("FIELD_LABEL_BOOK_PUBLISHER")
_("FIELD_LABEL_BOOK_PRICE")

# STUDENT FIELDS LABELS
_("FIELD_LABEL_STUDENT_FIRST_NAME")
_("FIELD_LABEL_STUDENT_MIDDLE_NAME")
_("FIELD_LABEL_STUDENT_LAST_NAME")
_("FIELD_LABEL_STUDENT_ADDRESS")
_("FIELD_LABEL_STUDENT_GENDER")
_("FIELD_LABEL_STUDENT_MOTHER_TONGUE")
_("FIELD_LABEL_STUDENT_BIRTH_DATE")
_("FIELD_LABEL_STUDENT_IS_DROPOUT")
_("FIELD_LABEL_STUDENT_HAS_ATTENDED_PRESCHOOL")

# READ SESSION FIELDS LABELS
_("FIELD_LABEL_READ_SESSION_DATE_TIME")
_("FIELD_LABEL_READ_SESSION_IS_VERIFIED")
_("FIELD_LABEL_READ_SESSION_IS_CANCELLED")
_("FIELD_LABEL_READ_SESSION_NOTES")
_("FIELD_LABEL_READ_SESSION_TYPE")

# USER FIELDS LABELS
_("FIELD_LABEL_USER_FIRST_NAME")
_("FIELD_LABEL_USER_MIDDLE_NAME")
_("FIELD_LABEL_USER_LAST_NAME")
_("FIELD_LABEL_USER_EMAIL")
_("FIELD_LABEL_USER_USERNAME")
_("FIELD_LABEL_USER_PASSWORD")
_("FIELD_LABEL_USER_LANGUAGE")

# NGO FIELDS LABELS
_("FIELD_LABEL_NGO_NAME")
_("FIELD_LABEL_NGO_ADDRESS")

# LABEL for MODELS
_("LABEL_SCHOOL")
_("LABEL_CLASSROOM")
_("LABEL_ACADEMIC_YEAR")
_("BOOK FAIRY")
_("LABEL_NGO")
_("LABEL_READ_SESSION")
_("LABEL_STUDENT")
_("LABEL_USER")

# ADD SESSION LABEL
_("LABEL_ADD_READ_SESSION_RECURRENCE_PATTERN")
_("LABEL_ADD_READ_SESSION_ONE_TIME_SESSION")
_("LABEL_ADD_READ_SESSION_RECURRING")
_("LABEL_ADD_READ_SESSION_START_DATE")
_("LABEL_ADD_READ_SESSION_END_DATE")

# OTHER LABELS
_("LABEL_BOOK")
_("LABEL_STANDARD")
_("LABEL_DIVISION")
_("LABEL_LOGIN")
_("LABEL_ADD_NEW")
_("LABEL_SUBMIT")
_("LABEL_FILTERS")
_("LABEL_EVALUATED_BY_BOOK_FAIRY")
_("LABEL_VERIFIED_BY_SUPERVISOR")
_("LABEL_SESSION_DETAILS")
_("LABEL_STUDENT_DETAILS")
_("LABEL_NAME")
_("LABEL_ATTENDANCE")
_("LABEL_PRESENT")
_("LABEL_COMMENTS")
_("LABEL_LEVEL")
_("LABEL_STUDENT_NAME")
_("LABEL_SAVE")
_("LABEL_SUBMIT")
_("CAMERA_PERMISSION_REQUIRED")
_("STUDENT_MUST_BE_MARKED_PRESENT_BEFORE_ADDING_BOOK")
_("BOOK_NOT_FOUND")
_("BOOK_ALREADY_ADDED")
_("SEARCH_BOOK")
_("SELECT_LEVEL")
_("NO_COMMENTS_ERROR")
_("NO_LEVEL_ERROR")
_("DATA_NOT_SAVED")
_("DISCARD_ALL_CHANGES")
_("YES")
_("NO")
_("SCAN_BOOK_CODE")
_("MEMORY_LEAK_ERROR")
_("NO_NETWORK_DATA_STORED_OFFLINE")
_("ALL_STUDENTS_NOT_EVALUATED_ERROR")
_("SESSION_FRAGMENT_TITLE")
_("BOOK_FRAGMENT_TITLE")
_("RESET_PASSWORD_TITLE")
_("LABEL_OLD_PASSWORD")
_("LABEL_NEW_PASSWORD")
_("LABEL_CONFIRM_PASSWORD")
_("ALL_PASSWORDS_FIELD_ERROR")
_("CONFIRM_PASSWORD_ERROR")
_("NO_NETWORK")
_("OLD_PASSWORD_IS_WRONG")
_("CHANGED_PASSWORD")
_("CHANGE_LANGUAGE_TITLE")
_("LABEL_PENDING_SESSIONS")
_("LABEL_EVALUATED_SESSIONS")
_("LABEL_UPCOMING_SESSIONS")
_("LABEL_SYNC_BOOKS")
_("SYNC_ERROR")
_("LABEL_NO_SESSIONS")
_("LABEL_LEND")
_("LABEL_LENT")
_("LABEL_COLLECT")
_("LABEL_COLLECTED")
_("LABEL_LOGOUT")
_("LABEL_EXIT_APP")
_("LABEL_LOGOUT_ERROR")
_("LABEL_OK")
_("LABEL_LOGOUT_SAVE_MESSAGE")
_("SYNC_ALREADY_RUNNING")
_("SYNC_STARTED")
_("SYNC_COMPLETE")

# ADD USER
_("FIELD_LABEL_USER_TYPE")

# STANDARDS
_("STANDARD_I")
_("STANDARD_II")
_("STANDARD_III")
_("STANDARD_IV")
_("STANDARD_V")
_("STANDARD_VI")
_("STANDARD_VII")
_("STANDARD_VIII")
_("STANDARD_IX")
_("STANDARD_X")

# CLASSROOM_STANDARD
_("FIELD_LABEL_CLASSROOM_STANDARD")
_("FIELD_LABEL_CLASSROOM_DIVISION")

_("READ_SESSION_REGULAR")
_("READ_SESSION_EVALUATION")

# INVENTORY
_("FIELD_LABEL_INVENTORY_SERIAL_NUMBER")
_("FIELD_LABEL_INVENTORY_STATUS")
_("FIELD_LABEL_INVENTORY_YEAR_OF_PURCHASE")

# LEVEL
_("FIELD_LABEL_LEVEL_RANK")
_("FIELD_LABEL_RANK_MR_IN")
_("FIELD_LABEL_RANK_EN_IN")

# OTHER
_("LABEL_ACTIONS")

# BOOK LEVELS LABELS
_("BOOK_LEVEL_1")
_("BOOK_LEVEL_2")
_("BOOK_LEVEL_3")
_("BOOK_LEVEL_4")

PROTECTION_OPTIONS = {
    'delete_rows': True,
    'insert_rows': True,
    'select_locked_cells': True,
}

_("LABEL_IMPORT")
_("LABEL_EXPORT")
_("LABEL_DEACTIVATE")

_("FIELD_LABEL_BOOK_NAME")
_("FIELD_LABEL_BOOK_LEVEL")
_("FIELD_LABEL_BOOK_AUTHOR")

_("FIELD_LABEL_READ_SESSION_TYPE")
_("READ_SESSION_BOOK_LENDING")
_("READ_SESSION_REGULAR")
_("READ_SESSION_EVALUATION")

_("FIELD_LABEL_CHANGE_PASSWORD")

_("LABEL_ACADEMIC_YEAR_START_TIME")
_("LABEL_ACADEMIC_YEAR_END_TIME")

_("FIELD_LABEL_FORGOT_PASSWORD ")
_("LABEL_EDIT")
_("FIELD_LABEL_SCHOOL_SCHOOL_CATEGORY")

_("LABEL_NO_OF_STUDENT")
_("LABEL_INVENTORY")
_("FIELD_LABEL_INVENTORY_SERIAL_NUMBER")
_("FIELD_LABEL_INVENTORY_STATUS")

_("LABEL_MARK_AS_DROPOUT")
_("LABEL_SCHEDULED_AT")

_("LABEL_SESSION_START_TIME")
_("LABEL_SESSION_END_TIME")

_("LABEL_EVALUATED_BY")
_("LABEL_SUBMITTED_BY")
_("LABEL_VERIFIED_BY")
_("SUPERVISOR")
_("NGO ADMIN")
_("FUNDER")

_("LABEL_PRESENT")
_("LABEL_LEVEL")
_("LABEL_COMMENTS")
_("LABEL_DETAILS")

_("LABEL_RESET_PASSWORD")
_("LABEL_CHANGE_PASSWORD")
_("LABEL_OLD_PASSWORD")
_("LABEL_NEW_PASSWORD")
_("LABEL_CONFIRM_PASSWORD")

_("LABEL_CLEAR")
_("LABEL_MANAGEMENT")
_("LABEL_SELECT_SUPERVISOR")
_("LABEL_YOUR_PROFILE")
_("LABEL_WELCOME")
_("LABEL_SETTINGS")
_("LABEL_CANCEL")
_("LABEL_EXCEL_FORMAT")
_("LABEL_FILE_IMPORT")
_("LABEL_DELETE_ACTION")
_("LABEL_YES")
_("LABEL_ADD_ADMIN")
_("LABEL_DEACTIVATE_NGO")
_("LABEL_REMOVE")

_("LABEL_CHANGE_LANGUAGE")
_("LABEL_UPLOAD")
_("LABEL_CHOOSE_FILE")
_("LABEL_PENDING_SESSIONS")
_("LABEL_EVALUATED_NOT_VERIFIED_SESSIONS")
_("LABEL_UPCOMING_SESSIONS")
_("LABEL_EVALUATED_SESSIONS_BY_BOOK_FAIRY")
_("LABEL_UNEVALUATED_SESSIONS_BY_BOOK_FAIRY")
_("LABEL_ALL_SESSION")
_("LABEL_DETAILS")
_("LABEL_BOOK_AND_INVENTORY_DETAILS")

_("LABEL_SELECT_LANGUAGE")
_("LABEL_NOTES")
_("LABEL_SEARCH_BY_SERIAL_NO")
_("LABEL_STUDENT_OF")
_("LABEL_BOOK_FAIRY")
_("ABOUT_TITLE")

_("LABEL_SELECT")
_("LABEL_NGO_DETAILS")
_("LABEL_REPEAT_ON_EVERY_WEEK")
_("LABEL_CANCEL_SESSION")
_("LABEL_FORGOT_PASSWORD_MESSAGE")
_("LABEL_RESET_PASSWORD_SUCCESS")
_("LABEL_FORGOT_PASSWORD_SUCCESS")
