#  Copyright (c) 2020. Maverick Labs
#    This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU Affero General Public License as,
#   published by the Free Software Foundation, either version 3 of the
#   License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Generated by Django 2.1.5 on 2019-05-02 05:08

from django.db import migrations, models
import django.db.models.deletion
import schools.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic_years', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassroomFunders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('last_modification_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'classroom_funders',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=schools.models.generate_school_key, max_length=3, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=300)),
                ('pin_code', models.IntegerField()),
                ('ward_number', models.IntegerField()),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('school_number', models.IntegerField(blank=True, null=True)),
                ('organization_name', models.CharField(max_length=100)),
                ('year_of_intervention', models.DateField()),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('last_modification_time', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'schools',
            },
        ),
        migrations.CreateModel(
            name='SchoolAcademicYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_classes', models.IntegerField(blank=True, null=True)),
                ('number_of_classrooms_available', models.IntegerField(blank=True, null=True)),
                ('number_of_classrooms_used', models.IntegerField(blank=True, null=True)),
                ('number_of_teachers', models.IntegerField(blank=True, null=True)),
                ('number_of_toilets', models.IntegerField(blank=True, null=True)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('last_modification_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'school_academic_years',
            },
        ),
        migrations.CreateModel(
            name='SchoolCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('SCHOOL_CATEGORY_BOYS', 'Boys'), ('SCHOOL_CATEGORY_GIRLS', 'Girls'), ('SCHOOL_CATEGORY_CO_ED', 'CO-ED')], max_length=100)),
                ('is_active', models.BooleanField(blank=True, default=True)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('last_modification_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'school_categories',
            },
        ),
        migrations.CreateModel(
            name='SchoolFunders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('last_modification_time', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academic_years.AcademicYear')),
            ],
            options={
                'db_table': 'school_funders',
            },
        ),
        migrations.CreateModel(
            name='SchoolMedium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('SCHOOL_MEDIUM_ENGLISH', 'English'), ('SCHOOL_MEDIUM_MARATHI', 'Marathi'), ('SCHOOL_MEDIUM_URDU', 'Urdu')], max_length=100)),
                ('is_active', models.BooleanField(blank=True, default=True)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('last_modification_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'school_mediums',
            },
        ),
        migrations.CreateModel(
            name='SchoolType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('SCHOOL_TYPE_PCMC', 'PCMC'), ('SCHOOL_TYPE_PMC', 'PMC'), ('SCHOOL_TYPE_ZP', 'ZP'), ('SCHOOL_TYPE_PRIVATE', 'Private')], max_length=100)),
                ('is_active', models.BooleanField(blank=True, default=True)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('last_modification_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'school_types',
            },
        ),
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(blank=True, default=True)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('last_modification_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'standards',
            },
        ),
    ]
