#  Copyright (c) 2020. Maverick Labs
#    This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU Affero General Public License as,
#   published by the Free Software Foundation, either version 3 of the
#   License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Generated by Django 2.1.5 on 2019-05-02 05:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ngos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classrooms', '0002_auto_20190502_0508'),
        ('schools', '0001_initial'),
        ('academic_years', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolfunders',
            name='funder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schoolfunders',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schools.School'),
        ),
        migrations.AddField(
            model_name='schoolacademicyear',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academic_years.AcademicYear'),
        ),
        migrations.AddField(
            model_name='schoolacademicyear',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schools.School'),
        ),
        migrations.AddField(
            model_name='school',
            name='medium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schools.SchoolMedium'),
        ),
        migrations.AddField(
            model_name='school',
            name='ngo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ngos.NGO'),
        ),
        migrations.AddField(
            model_name='school',
            name='school_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schools.SchoolCategory'),
        ),
        migrations.AddField(
            model_name='school',
            name='school_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schools.SchoolType'),
        ),
        migrations.AddField(
            model_name='classroomfunders',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academic_years.AcademicYear'),
        ),
        migrations.AddField(
            model_name='classroomfunders',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classrooms.Classroom'),
        ),
        migrations.AddField(
            model_name='classroomfunders',
            name='funder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
