#  Copyright (c) 2020. Maverick Labs
#    This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU Affero General Public License as,
#   published by the Free Software Foundation, either version 3 of the
#   License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Generated by Django 2.1.5 on 2019-05-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0006_auto_20190506_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolmedium',
            name='name',
            field=models.CharField(choices=[('SCHOOL_MEDIUM_ENGLISH', 'English'), ('SCHOOL_MEDIUM_MARATHI', 'Marathi'), ('SCHOOL_MEDIUM_URDU', 'Urdu'), ('SCHOOL_MEDIUM_HINDI', 'Hindi'), ('SCHOOL_MEDIUM_KANNADA', 'Kannada')], max_length=100),
        ),
    ]
