#  Copyright (c) 2020. Maverick Labs
#    This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU Affero General Public License as,
#   published by the Free Software Foundation, either version 3 of the
#   License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Generated by Django 2.1.5 on 2019-05-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='level',
            field=models.CharField(blank=True, choices=[('BOOK_TYPE_1', 'BOOK_LEVEL_1'), ('BOOK_LEVEL_2', 'BOOK_LEVEL_2'), ('BOOK_LEVEL_3', 'BOOK_LEVEL_3'), ('BOOK_LEVEL_4', 'BOOK_LEVEL_4')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='added_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
